# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d66381ac98194193b29e2d42a09435e3c627d33d9646158c64d1290c9425897a284b619498a401b7c3fca5e40f043a942a9815e3bc5da7c784aedd9fe08b79e0

test:
  secret_key_base: cf929ad86dd81a2c11249f3ca6ff8d3b29382c6c7af58e1ffa0965b39fd7a9d5ba066c30ec8a7eb80b4f519cbbae355d43699de0cbcc869fcd554004633052cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
